language: python
python:
  - "3.5"
  
env:
  - BOTO_CONFIG=/tmp/nowhere
  
before_install: 
  sudo apt-get install python-scipy 

install: "pip install -r requirements.txt"
# command to run tests
script: python test.py
